# Generated by Django 6.0 on 2026-01-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('club', 'Club')], default='regular', max_length=10, null=True),
        ),
    ]
