# Generated by Django 6.0 on 2025-12-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_type',
            field=models.CharField(blank=True, choices=[('academic', 'Academic'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('technical', 'Technical'), ('arts', 'Arts'), ('social', 'Social'), ('professional', 'Professional'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
