# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_club_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='board_member_photos/'),
        ),
    ]
